### ISSUE TITLE
SlidableLayout 竖向嵌套 Nestedscrollview ，翻到最后一页后，在往下翻会出现下边出现空白现象。

### ISSUE THREAD

**Issue by jackpanz** [YvesCheung/SlidableLayout#10]
SlidableLayout 竖向嵌套 Nestedscrollview ，翻到最后一页后，在往下翻会出现下边出现空白现象。 
如果用普通的Scrollview翻到最后一页后是不能再翻动的。但是用Nestedscrollview翻到最后一页还可以翻出空白位置。

<img width="292" alt="微信图片_20200316010011" src="https://user-images.githubusercontent.com/8186829/76706324-92a3a000-6721-11ea-90a5-a0548befa1f3.png">

**Comment by jackpanz** [comment]
implementation 'com.github.YvesCheung:SlidableLayout:1.1.0.x'

**Comment by YvesCheung** [comment]
b5ecdfd4002c4257f0f6812793d6256ba51e3899 Fix this bug. 
`implementation 'com.github.YvesCheung:SlidableLayout:1.1.1.x'`
