### ISSUE TITLE
gradle引入后编译报错

### ISSUE THREAD

**Issue by ArtisanM** [YvesCheung/SlidableLayout#13]
More than one file was found with OS independent path 'META-INF/lib_release.kotlin_module'

**Comment by YvesCheung** [comment]
这是这个库打包时使用了moduleName ‘lib’ 来生成 kotlin_module文件导致的，如果有多个库都叫`lib`就会报这个错。
可以先在application模块的 `build.gradle` 文件中添加这段代码解决这个错误：

```kotlin
android {
    packagingOptions {
        exclude 'META-INF/lib_release.kotlin_module'
    }
}
```

**Comment by YvesCheung** [comment]
bcbac671ef050a9ddaa9a4b8654ed0683a890e8c
修改打包时的模块名字，从根本上修复kotlin_module文件重名的问题。version 1.1.3
