### ISSUE TITLE
SlidableLayout背景透明时快速滑动

### ISSUE THREAD

**Issue by ArtisanM** [YvesCheung/SlidableLayout#14]
比如rootview有个背景，然后slidablayout作为其子view透明背景，fragmentAdapter创建出来的fragment有背景，在快速滑动时会闪一下，露出rootview的内容。滑的速度越快，露出的那一下露的越多

**Comment by ArtisanM** [comment]
找到原因了，应该就是因为fragment attach到view上慢一拍导致的。因为我给SlideFragmentAdapter的onCreateViewHolder里new出来的viewGroup设置个背景就不出现这个问题了。
这里有什么优化的办法吗

**Comment by YvesCheung** [comment]
如果是因为慢一拍的话，试试把 `SlideFragmentAdapter` 的
`commitAllowingStateLoss` 改成 `commitNowAllowingStateLoss` ?

**Comment by YvesCheung** [comment]
4709921a94d5f42e614796cfbb27bdf24bc91972 不知道能否解决

**Comment by ArtisanM** [comment]
谢谢 这个commit顺便还改好了在onCreateViewHolder里add fragment导致的IllegalArgumentException: No view found for id异常
