### ISSUE TITLE
仿知乎上拉阅读全文的效果

### ISSUE THREAD

**Issue by TrebleZ** [YvesCheung/SlidableLayout#15]
这个库可以用来实现仿知乎上拉阅读全文的效果吗

**Comment by YvesCheung** [comment]
需要修改一下上拉后的行为

**Comment by TrebleZ** [comment]
这边想做成上拉切换整个页面的动效，发现正常切换一次后，再上拉会出现半个之前的view的状态页面，复用的itemview怎么清除之前view的状态

**Comment by TrebleZ** [comment]
没事了。这边不应该用这个库去做那个效果。。。我这边关闭了，谢谢楼主的控件很棒
