### ISSUE TITLE
刷用刷新控件加载下一页时，视频会闪烁一下

### ISSUE THREAD

**Issue by a9151357635** [YvesCheung/SlidableLayout#16]
![image](https://user-images.githubusercontent.com/46913850/174735665-ec349ae7-e09b-4e53-9831-d7fa08757883.png)

如图，希望可以跟adapter一样，添加新数据时，不会造成视频闪烁

**Comment by YvesCheung** [comment]
刚刚看了一下代码 addLast这种场景应该是不用调notifyDataSetChanged的，
clear这种要把当前View改掉的，才需要notifyDataSetChanged。
这个api是设计得不太科学，现在的我看回去也觉得当年这么写有问题。

**Comment by YvesCheung** [comment]
把notifyDataSetChanged放到cPage==1这个分支里面试试。

**Comment by a9151357635** [comment]
> 把notifyDataSetChanged放到cPage==1这个分支里面试试。

这个试过啦，不行的，最近实在是太忙啦，还有一个情况就是：滑动到底部，有loadmore的时候，其实canSlideTo滑动到next的，但是next是没有值的，但是还是走了onBindView onViewComplete，这就造成了，我原本不想做的时候，帮我做了，加判断能有不太好，建议多加一个方法，针对这种情况的
<img width="725" alt="image" src="https://user-images.githubusercontent.com/46913850/175051067-5eaecc18-1636-4efe-b054-1aff7bda6150.png">

**Comment by a9151357635** [comment]
> 刚刚看了一下代码 addLast这种场景应该是不用调notifyDataSetChanged的， clear这种要把当前View改掉的，才需要notifyDataSetChanged。 这个api是设计得不太科学，现在的我看回去也觉得当年这么写有问题。

是的啊，其实最好是adapter兼容adapter的功能。3171316408这是我Q,

**Comment by a9151357635** [comment]
感谢指导，发现了问题了
