### ISSUE TITLE
[建议]可以优化一下切换的过渡动画

### ISSUE THREAD

**Issue by BigTimo** [YvesCheung/SlidableLayout#3]
使用了一下，很不错。但是过渡动画没有ViewPager自然。
建议动画时间DEFAULT_DURATION调整为550，设置动画差值器DecelerateInterpolator。

**Comment by YvesCheung** [comment]
好的建议。
5aa47710a979383eac7e59baf06e1903730926ba
参照android-28sdk的ViewPager重写过渡动画部分。
