### ISSUE TITLE
[BUG]项目与库v4包版本不一致报错。库中建议使用 compileOnly "com.android.support:support-v4:28.0.0"

### ISSUE THREAD

**Issue by BigTimo** [YvesCheung/SlidableLayout#4]
如果引入的项目 版本不是28.0.0 会报错：
Android dependency 'com.android.support:support-fragment' has different version for the compile (27.1.1) and runtime (28.0.0) classpath. You should manually set the same version via DependencyResolution。

建议 使用 compileOnly "com.android.support:support-v4:28.0.0"

**Comment by YvesCheung** [comment]
Fix in 1.0.4
support依赖改为compileOnly。
添加AndroidX依赖版本。
