### ISSUE TITLE
嵌套滚动被SlidableLayout拦截，？

### ISSUE THREAD

**Issue by aer874475222** [YvesCheung/SlidableLayout#8]
我用SlidableLayout做了一个上下滚动的布局，然后在内部视图item_view里面再嵌套一个SlidableLayout做左右滑动，内部的SlidableLayout可以左右滑动，外部的SlidableLayout上下滑动就被拦截了？

**Comment by YvesCheung** [comment]
version 1.1.0 支持作为[NestedScrollingParent]的嵌套滑动
[同向嵌套滑动demo](https://github.com/YvesCheung/SlidableLayout/blob/master/app/src/main/java/com/yy/mobile/slidablelayout/DemoForNestedScroll.kt)
[异向嵌套滑动demo](https://github.com/YvesCheung/SlidableLayout/blob/master/app/src/main/java/com/yy/mobile/slidablelayout/DemoForCrossScroll.kt)
