### ISSUE TITLE
无法刷新，没有刷新相关的方法

### ISSUE THREAD

**Issue by TracyEminem** [YvesCheung/SlidableLayout#9]
集成完了发现这个没有提供刷新方法，刷新列表添加完数据后，第一页的数据必须得滑动后再滑动回来才会刷新。

**Comment by TracyEminem** [comment]
刷新后也不会回调任何生命周期及状态切换方法，很难处理这个刷新完第一页被复用没法更新的问题

**Comment by TracyEminem** [comment]
有啥好的解决方法吗？我已经把代码集成到项目中，现在有点进退两难

**Comment by YvesCheung** [comment]
b56cf2a7f87819e67df0010cfacb6575bdc65152
添加了 `SlidableLayout#notifyDataSetChanged` 方法用于刷新布局

[DemoForDataSetChanged](https://github.com/YvesCheung/SlidableLayout/blob/master/app/src/main/java/com/yy/mobile/slidablelayout/DemoForDataSetChanged.kt) 新增了下拉刷新当前页面的demo

这个提交在1.0.7版本中已发布
旧版本可以通过再调用一次setAdapter来实现同样的效果
